ecommerce/carts/urls.py
from django.contrib import admin
from django.urls import path

from .views import (
        cart_home,
        cart_update,
        checkout,
        order_success,
    )

urlpatterns = [
    path('', cart_home, name="home"),
    path('checkout/', checkout, name="checkout"),
    path('update/', cart_update, name="update"),
    path('success/', order_success, name="success"),
]

ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import include
from django.contrib.auth.views import LogoutView
from django.contrib import admin
from django.urls import path

from .views import home_page, about_page, contact_page
from carts.views import cart_detail_api_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from accounts.views import login_page, register_page, login_guest_view


urlpatterns = [
    path('', home_page, name="home"),
    path('about/', about_page, name="about"),
    path('contact/', contact_page, name="contact"),
    path('login/', login_page, name="login"),
    path('register/login_guest_view/', login_guest_view, name="guest_register"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', register_page, name="register"),
    path('api/cart/', cart_detail_api_view, name="api-cart"),

    path('checkout/address/create/', checkout_address_create_view, name="checkout_address_create"),
    path('checkout/address/reuse/', checkout_address_reuse_view, name="checkout_address_reuse"),

    path('cart/', include(("carts.urls", "carts"), namespace="cart")),
    path('products/', include(("products.urls", "products"), namespace="products")),
    path('search/', include(("search.urls", "search"), namespace="search")),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/products/urls.py
from django.contrib import admin
from django.urls import path

from .views import (
        ProductListView,
        ProductDetailView,
        ProductFeaturedListView,
        ProductFeaturedDetailView
    )

urlpatterns = [
    path('', ProductListView.as_view(), name="list"),
    path('featured/', ProductFeaturedListView.as_view()),
    path('featured/<int:pk>', ProductFeaturedDetailView.as_view()),
    path('<slug:slug>', ProductDetailView.as_view(), name="slug_view"),
]

ecommerce/templates/base/css.html
{% load static %}
<link href="https://fonts.googleapis.com/css?family=Rubik:400,700" rel="stylesheet">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

ecommerce/templates/base/js.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.5.0.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

ecommerce/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'products:list' as product_url %}
{% url 'contact' as contact_url %}
{% url 'about' as about_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{{ home_url }}">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %} active {%endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == product_url %} active {% endif %}">
        <a class="nav-link" href="{{ product_url }}">Products</a>
      </li>
      <li class="nav-item {% if request.path == contact_url %} active {%endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contact</a>
      </li>
      <li class="nav-item {% if request.path == about_url %} active {%endif %}">
        <a class="nav-link" href="{{ about_url }}">About</a>
      </li>
        {% if request.user.is_authenticated == False %}
            <li class="nav-item {% if request.path == login_url %} active {%endif %}">
                <a class="nav-link" href="{{ login_url }}">Login</a>
            </li>
            <li class="nav-item {% if request.path == register_url %} active {%endif %}">
                <a class="nav-link" href="{{ register_url }}">Register</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ logout_url }}">Logout</a>
            </li>
        {% endif %}

      <li class="nav-item {% if request.path == cart_url %} active {%endif %}">
          <a class="nav-link" href="{{ cart_url }}"><span class="nav-cart-count">{{ request.session.cart_items }}</span> <i class="fas fa-shopping-cart"></i></a>
      </li>
    </ul>
    {% include "snippets/search_form.html" %}
  </div>
</nav>