ecommerce/carts/urls.py
from django.contrib import admin
from django.urls import path

from .views import (
        cart_home,
        cart_update,
        checkout,
        order_success,
    )

urlpatterns = [
    path('', cart_home, name="home"),
    path('checkout/', checkout, name="checkout"),
    path('update/', cart_update, name="update"),
    path('success/', order_success, name="success"),
]

ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import include
from django.contrib.auth.views import LogoutView
from django.contrib import admin
from django.urls import path

from .views import home_page, about_page, contact_page
from carts.views import cart_detail_api_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from accounts.views import login_page, register_page, login_guest_view


urlpatterns = [
    path('', home_page, name="home"),
    path('about/', about_page, name="about"),
    path('contact/', contact_page, name="contact"),
    path('login/', login_page, name="login"),
    path('register/login_guest_view/', login_guest_view, name="guest_register"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', register_page, name="register"),
    path('api/cart/', cart_detail_api_view, name="api-cart"),

    path('checkout/address/create/', checkout_address_create_view, name="checkout_address_create"),
    path('checkout/address/reuse/', checkout_address_reuse_view, name="checkout_address_reuse"),

    path('cart/', include(("carts.urls", "carts"), namespace="cart")),
    path('products/', include(("products.urls", "products"), namespace="products")),
    path('search/', include(("search.urls", "search"), namespace="search")),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/carts/models.py
from django.db import models
from django.conf import settings

from django.db.models.signals import pre_save, m2m_changed

User = settings.AUTH_USER_MODEL

from products.models import Product


class CartManager(models.Manager):

    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_cart = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            new_cart = True
            cart_obj = self.new(user=request.user)
            request.session["cart_id"] = cart_obj.id
        return cart_obj, new_cart

    def new(self, user):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user = models.ForeignKey(User, models.SET_NULL, null=True, blank=True)
    products = models.ManyToManyField(Product, blank=True)
    subtotal = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)


def cart_m2m_changed_receiver(sender, instance, action, *args, **kwargs):
    if action in ("post_add", "post_remove", "post_clear"):
        products = instance.products.all()
        subtotal = 0
        for x in products:
            subtotal += x.price
        instance.subtotal = subtotal
        instance.save()


m2m_changed.connect(cart_m2m_changed_receiver, sender=Cart.products.through)


def cart_pre_save_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = instance.subtotal
    else:
        instance.total = 0.00


pre_save.connect(cart_pre_save_receiver, sender=Cart)

ecommerce/carts/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse

from accounts.forms import LoginForm, GuestForm
from addresses.forms import AddressForm

from addresses.models import Address
from accounts.models import GuestEmailModel
from orders.models import Order
from products.models import Product
from billing.models import BillingProfile

from .models import Cart


def cart_detail_api_view(request):
    cart_obj, status = Cart.objects.new_or_get(request)
    products = [{
                    "id": product.id,
                    "name": product.title,
                    "url": product.get_absolute_url(),
                    "price": product.price
                } for product in cart_obj.products.all()]
    cart_data = {"products": products, "subtotal": cart_obj.subtotal, "total": cart_obj.total}
    return JsonResponse(cart_data)


def cart_home(request):
    cart_obj, status = Cart.objects.new_or_get(request)
    context = {
        "cart": cart_obj,
    }
    return render(request, "carts/home.html", context)


def cart_update(request):
    product_id = request.POST.get("product_id")
    if product_id:
        qs = Product.objects.filter(id=product_id)
        if qs.count() == 1:
            product_obj = qs.first()
            cart_obj, new_obj = Cart.objects.new_or_get(request)
            if product_obj in cart_obj.products.all():
                cart_obj.products.remove(product_obj)
                added = False
            else:
                cart_obj.products.add(product_obj)
                added = True
            request.session["cart_items"] = cart_obj.products.count()
            if request.is_ajax():
                json_data = {
                    "added": added,
                    "removed": not added,
                    "cartItemCount": cart_obj.products.count()
                }
                return JsonResponse(json_data)
    return redirect("cart:home")


def checkout(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    if cart_created:
        return redirect("cart:home")
    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)

    order_obj = None
    address_qs = None
    if billing_profile:
        if request.user.is_authenticated:
            address_qs = Address.objects.filter(billing_profile=billing_profile)
        order_obj, created = Order.objects.new_or_get(cart_obj, billing_profile)
        billing_address_id = request.session.get("billing_address_id", None)
        shipping_address_id = request.session.get("shipping_address_id", None)
        print(shipping_address_id)
        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session['shipping_address_id']
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id)
            del request.session['billing_address_id']
        if shipping_address_id or billing_address_id:
            order_obj.save()

    if request.method == "POST":
        is_done = order_obj.check_done()
        if is_done:
            order_obj.mark_paid()
            request.session["cart_items"] = 0
            del request.session["cart_id"]
            return redirect("cart:success")

    context = {
        "object": order_obj,
        "billing_profile": billing_profile,
        "login_form": login_form,
        "guest_form": guest_form,
        "address_form": address_form,
        "address_qs":address_qs,
    }
    return render(request, "carts/checkout.html", context)


def order_success(request):
    return render(request, "carts/order_success.html", {})

ecommerce/carts/templates/carts/checkout.html
{% extends "base.html" %}

{% block content %}
{{ object.order_id }} -- {{ object.cart }}


{% if not billing_profile %}
<div class="row">
    <div class="col-12 col-md-6">
        <p class="lead">Login</p>
        {% include 'snippets/form.html' with form=login_form next=request.build_absolute_uri %}
    </div>
    <div class="col-12 col-md-6">
        <p class="lead">Continue as Guest</p>
        {% url 'guest_register' as login_guest_url %}
        {% include 'snippets/form.html' with form=guest_form next=request.build_absolute_uri action_url=login_guest_url %}
    </div>
</div>

{% else %}

    {% if not object.shipping_address %}
        <div class="row">
            <div class="col-12">
                <p class="lead">Shipping Address</p>
                <hr/>
            </div>
            <div class="col-6">
                {% url 'checkout_address_create' as checkout_address_create %}
                {% include 'addresses/snippets/form.html' with form=address_form next=request.build_absolute_uri action_url=checkout_address_create address_type='shipping' %}
            </div>
            <div class="col-6">
                {% url 'checkout_address_reuse' as checkout_address_reuse %}
                {% include 'addresses/snippets/prev_addresses.html' with address_qs=address_qs next=request.build_absolute_uri address_type='shipping' action_url=checkout_address_reuse %}
            </div>
        </div>
    {% elif not object.billing_address %}
        <div class="row">
            <div class="col-12">
                <p class="lead">Billing Address</p>
                <hr/>
            </div>
            <div class="col-6">
                {% url 'checkout_address_create' as checkout_address_create %}
                {% include 'addresses/snippets/form.html' with form=address_form next=request.build_absolute_uri action_url=checkout_address_create address_type='billing' %}
            </div>
            <div class="col-6">
                {% url 'checkout_address_reuse' as checkout_address_reuse %}
                {% include 'addresses/snippets/prev_addresses.html' with address_qs=address_qs next=request.build_absolute_uri address_type='billing' action_url=checkout_address_reuse %}
            </div>
        </div>
    {% else %}
        <h1>Finally Checkout</h1>
        <p>Cart Items: {% for product in object.cart.products.all %} {{ product }}{% if not forloop.last %},{% endif %} {% endfor %} </p>
        <p>Shipping Address: {{ object.shipping_address.get_address }}</p>
        <p>Billing Address: {{ object.shipping_address.get_address }}</p>
        <p>Shipping Total: {{ object.shipping_total }}</p>
        <p>Cart Total: {{ object.cart.total }}</p>
        <p>Total: {{ object.total }}</p>
        <form class="form" method="POST" method=""> {% csrf_token %}
            <button type="submit" class="btn btn-success">Checkout</button>
        </form>
    {% endif %}}
{% endif %}

{% endblock %}

ecommerce/carts/templates/carts/home.html
{% extends "base.html" %}

{% block content %}
<h1>Cart</h1>

{% if cart.products.exists %}
<div class="container">
<table class="table cart-home">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Product Name</th>
      <th scope="col">Price</th>
    </tr>
  </thead>
  <tbody class="cart-body">
  {% for product in cart.products.all %}
    <tr class="cart-products">
      <th scope="row">{{ forloop.counter }}</th>
      <td><a href="{{ product.get_absolute_url }}"> {{ product.title }}</a> <small>{% include 'product/snippets/update_cart.html' with product=product cart=cart in_cart=True%}</small></td>
      <td>{{ product.price }}</td>
    </tr>
  {% endfor %}
    <tr>
      <td colspan="2"></td>
        <td><b>Subtotal </b> <span class="cart-subtotal">{{ cart.subtotal }}</span> </td>
    </tr>
    <tr>
      <td colspan="2"></td>
        <td><b>Total </b> <span class="cart-total">{{ cart.total }}</span></td>
    </tr>
    <tr>
      <td colspan="2"></td>
        <td><a class='btn btn-lg btn-success' href="{% url 'cart:checkout' %}">Checkout</a></td>
    </tr>
  </tbody>
</table>
    </div>
{% else %}
    <p>Cart is empty.</p>
{% endif %}
{% endblock %}

ecommerce/carts/templates/carts/order_success.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-12">
        <h2>Successfully Order</h2>
    </div>
</div>
{% endblock %}